### ISSUE TITLE
OSB_build script error

### ISSUE THREAD

**Issue by Mahi2011** [biemond/soa_tools#1]
I took scriprt from soa/tools:

i need to export OSB projects jar .below script should work for me ...but iam getting error

string trim errors:
unable to invoke WLST ...

script:

---

<?xml version="1.0" encoding="WINDOWS-1252"?>
-<project name="ConfigExport">
 <property file="./build.properties"/> <property name="eclipse.home" value="${fmw.home}/oepe"/> <property name="weblogic.home" value="${fmw.home}/wlserver_10.3"/> <property name="metadata.dir" value="${workspace.dir}/.metadata"/> <property name="osb.home" value="${fmw.home}/Oracle_OSB1"/> <property name="domain.export.script" value="export.py"/> <property name="domain.import.script" value="import.py"/>

<target name="exportFromOSB"> -<wlst arguments="${wls.username} ${wls.password} ${wls.server} ${export.project} ${export.jar} ${export.customFile}" failOnError="false" debug="true" fileName="${domain.export.script}"> <script> adminUser=sys.argv[1] adminPassword=sys.argv[2] adminUrl=sys.argv[3] exportJar = sys.argv[5] customFile = sys.argv[6] passphrase = "osb" project = sys.argv[4] connect(adminUser,adminPassword,adminUrl) domainRuntime() </script> </wlst> </target>

<target name="importToOSB"> -<wlst arguments="${wls.username} ${wls.password} ${wls.server} ${import.project} ${import.jar} ${import.customFile}" failOnError="false" debug="true" fileName="${domain.import.script}"> <script> adminUser=sys.argv[1] adminPassword=sys.argv[2] adminUrl=sys.argv[3] passphrase = "osb" project=sys.argv[4] importJar=sys.argv[5] customFile=sys.argv[6] connect(adminUser,adminPassword,adminUrl) domainRuntime() </script> </wlst> </target>

</project>

---

Please helpme how can i execute above script...do i need to follow any specific steps

---

**Comment by biemond** [comment]
Hi,

Do you have everything installed , WLS , OEPE and OSB .

Then can you check your environment variables  maybe generate a
wlfullclient and use that.
Good luck

Sent from my iPad

On 25 nov. 2011, at 20:50, Mahi2011
reply@reply.github.com
wrote:

**Comment by Mahi2011** [comment]
I am getting below error while executing ...

Scripts/Test/Out/sbconfig.jar" "D:/Build/OSB/Scripts/Test/Out/cust.xml"'
     [wlst] <WLSTTask> Adding weblogic to sys.argv
     [wlst] <WLSTTask> Adding weblogic1 to sys.argv
     [wlst] <WLSTTask> Adding t3://172.25.152.152:7001 to sys.argv
     [wlst] <WLSTTask> Adding ShowAccountBalance_SB to sys.argv
     [wlst] <WLSTTask> Adding D:/Build/OSB/Scripts/Test/Out/sbconfig.jar to sys.argv
     [wlst] <WLSTTask> Adding D:/Build/OSB/Scripts/Test/Out/cust.xml to sys.argv
     [wlst] <WLSTTask> sys.argv is ['export.py', 'weblogic', 'weblogic1', 't3://172.25.152.152:7001', 'ShowAccountBalance_SB', 'D:/Build/OSB/Scripts/Test/Out/sbconfig.jar', 'D:/Bui
ld/OSB/Scripts/Test/Out/cust.xml']
     [wlst] Traceback (innermost last):
     [wlst] Exception in thread "main" java.lang.IllegalStateException: Traceback (innermost last):
     [wlst](no code object) at line 0
     [wlst](no code object) at line 0
     [wlst] SyntaxError: ('invalid syntax', ('C:\Documents and Settings\475037\Local Settings\Temp\wlsttempfile97003897.py', 3, 12, 'adminUrl=t3://172.25.152.152:7001'))
     [wlst] SyntaxError: ('invalid syntax', ('C:\Documents and Settings\475037\Local Settings\Temp\wlsttempfile97003897.py', 3, 12, 'adminUrl=t3://172.25.152.152:7001'))
     [wlst]
     [wlst]
     [wlst]     at weblogic.management.scripting.WLSTInterpreterInvoker.printError(WLSTInterpreterInvoker.java:110)
     [wlst]     at weblogic.management.scripting.WLSTInterpreterInvoker.executePyScript(WLSTInterpreterInvoker.java:103)
     [wlst]     at weblogic.management.scripting.WLSTInterpreterInvoker.main(WLSTInterpreterInvoker.java:27)
     [wlst] Java Result: 1

**Comment by biemond** [comment]
Hi ,

Can you check the generated  py file and look at the invalid syntax
fault. Maybe this will give a glue

Sent from my iPad

On 27 nov. 2011, at 17:48, Mahi2011
reply@reply.github.com
wrote:

**Comment by Mahi2011** [comment]
I have verified the.py file but i couldn't find the syntax error.

it is showing error at admin URL ...but the syntax is correct..could you pls cross verify it once ....it is there in above

**Comment by skirankumars31** [comment]
Hi,
    I think you have to run setWLSEnv.cmd from C:\Oracle\Middleware\wlserver_10.3\server\bin before doing this.

Regards
Kiran
