### ISSUE TITLE
OSB build error - ClassDefError

### ISSUE THREAD

**Issue by vidhprak** [biemond/soa_tools#2]
java.lang.NoClassDefFoundError: com/bea/alsb/tools/configjar/ConfigJar
Caused by: java.lang.ClassNotFoundException: com.bea.alsb.tools.configjar.ConfigJar
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: com.bea.alsb.tools.configjar.ConfigJar.  Program will exit.
Exception in thread "main" [INFO] -------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] osb.source ......................................... FAILURE [  1.972 s]
[INFO] osb.source.reliablemessagews ....................... SKIPPED
[INFO] osb.source.xsdvalidation ........................... SKIPPED
[INFO] Parent Project ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

---

My Environment Oracle OSB PS6 or 11.1.1.7
Maven 3.2.5
JVM                         = JDK 1.6
Middleware home      = C:\Oracle\Middleware1
OSB & Oracle home = C:\Oracle\Middleware1\Oracle_OSB1
WebLogic home       = C:\Oracle\Middleware1\wlserver_10.3
Oepe home               = C:\Oracle\Middleware1\oepe_11.1.1.8.0

I also have the configjar.jar in location - C:\Oracle\Middleware1\Oracle_OSB1\tools\configjar

Could you please help !!

**Comment by Tapan2609** [comment]
Hi There,
On initial analysis i can tell that ,there is mismatch in version of OSB and OEPE.
I think you are using OSB is of 11.1.1.7 and OEPE is of 11.1.1.8(Higher than OSB).
Try to use OEPE of same version as that of OSB(11.1.1.7).
Note sure above issue is because of version mismatch. Let give a try..:)

Thanks,
Tapan
